In [1]:
#Data Analysis and Data Wrangling
import pandas as pd
import numpy as np
import random as rnd
import scipy.stats as stats

In [2]:
#Visualization
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
from sklearn import preprocessing
from sklearn.feature_extraction import DictVectorizer

import xgboost as xgb
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import ExtraTreesRegressor
from sklearn import linear_model

from sklearn.feature_extraction.text import TfidfTransformer

from sklearn.cross_validation import KFold
from sklearn.metrics import mean_squared_error

C:\Users\owner\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)

In [4]:
train=pd.read_csv("C:\\Users\\owner\\Documents\\Capstone Project-2\\train.csv")
test=pd.read_csv("C:\\Users\\owner\\Documents\\Capstone Project-2\\test_Comb.csv")
submission=pd.read_csv("C:\\Users\\owner\\Documents\\Capstone Project-2\\SS.csv")

In [5]:
test

,Unnamed: 0,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Comb
0,0,1000004,P00128942,M,46-50,7,B,2,0,1,11.0,NaN,1000004P00128942
1,1,1000009,P00113442,M,26-35,17,C,0,0,3,5.0,NaN,1000009P00113442
2,2,1000010,P00288442,F,36-45,1,B,4+,0,5,14.0,NaN,1000010P00288442
3,3,1000010,P00145342,F,36-45,1,B,4+,0,4,9.0,NaN,1000010P00145342
4,4,1000011,P00053842,F,26-35,1,C,1,0,4,5.0,12.0,1000011P00053842
5,5,1000013,P00350442,M,46-50,1,C,3,0,2,3.0,15.0,1000013P00350442
6,6,1000013,P00155442,M,46-50,1,C,3,0,1,11.0,15.0,1000013P00155442
7,7,1000013,P0094542,M,46-50,1,C,3,0,2,4.0,9.0,1000013P0094542
8,8,1000015,P00161842,M,26-35,7,A,1,0,10,13.0,16.0,1000015P00161842
9,9,1000022,P00067942,M,18-25,15,A,4+,0,5,14.0,NaN,1000022P00067942
10,10,1000026,P00046742,M,26-35,7,B,2,0,1,2.0,15.0,1000026P00046742
11,11,1000026,P00040042,M,26-35,7,B,2,0,5,NaN,NaN,1000026P00040042
12,12,1000026,P00196542,M,26-35,7,B,2,0,5,8.0,14.0,1000026P00196542
13,13,1000026,P00004542,M,26-35,7,B,2,0,5,8.0,NaN,1000026P00004542
14,14,1000028,P00159542,F,26-35,1,C,2,0,10,15.0,16.0,1000028P00159542
15,15,1000029,P00111542,M,36-45,7,C,1,0,2,17.0,NaN,1000029P00111542
16,16,1000033,P00121042,M,46-50,3,A,1,0,15,NaN,NaN,1000033P00121042
17,17,1000033,P00344442,M,46-50,3,A,1,0,5,8.0,14.0,1000033P00344442
18,18,1000034,P00265242,F,18-25,0,A,0,0,5,8.0,NaN,1000034P00265242
19,19,1000035,P0096642,M,46-50,1,C,4+,0,2,3.0,4.0,1000035P0096642
20,20,1000036,P00303042,M,26-35,3,B,0,0,5,NaN,NaN,1000036P00303042
21,21,1000036,P00059642,M,26-35,3,B,0,0,1,2.0,3.0,1000036P00059642
22,22,1000042,P00030842,M,26-35,8,C,0,0,1,2.0,15.0,1000042P00030842
23,23,1000045,P00346442,F,46-50,16,A,1,0,1,2.0,14.0,1000045P00346442
24,24,1000045,P00357242,F,46-50,16,A,1,0,5,NaN,NaN,1000045P00357242
25,25,1000045,P00284742,F,46-50,16,A,1,0,5,12.0,NaN,1000045P00284742
26,26,1000048,P00110842,M,26-35,4,B,3,0,1,2.0,5.0,1000048P00110842
27,27,1000048,P00251642,M,26-35,4,B,3,0,1,2.0,4.0,1000048P00251642
28,28,1000053,P00136742,M,26-35,0,B,1,0,1,14.0,16.0,1000053P00136742
29,29,1000053,P0097342,M,26-35,0,B,1,0,1,15.0,16.0,1000053P0097342
...,...,...,...,...,...,...,...,...,...,...,...,...,...
233569,233569,1005996,P00184242,F,26-35,0,B,1,0,9,15.0,NaN,1005996P00184242
233570,233570,1005996,P00045342,F,26-35,0,B,1,0,1,5.0,17.0,1005996P00045342
233571,233571,1006001,P00124642,F,26-35,7,A,0,0,16,NaN,NaN,1006001P00124642
233572,233572,1006002,P00121142,M,51-55,0,C,1,0,8,NaN,NaN,1006002P00121142
233573,233573,1006002,P00233542,M,51-55,0,C,1,0,1,15.0,NaN,1006002P00233542
233574,233574,1006002,P00226342,M,51-55,0,C,1,0,11,15.0,NaN,1006002P00226342
233575,233575,1006002,P00284842,M,51-55,0,C,1,0,1,8.0,17.0,1006002P00284842
233576,233576,1006003,P00313342,F,46-50,17,C,1,0,5,NaN,NaN,1006003P00313342
233577,233577,1006010,P00223542,M,36-45,0,C,1,0,1,8.0,17.0,1006010P00223542
233578,233578,1006013,P00020342,F,26-35,20,C,3,0,1,2.0,NaN,1006013P00020342
233579,233579,1006016,P00014842,M,46-50,1,B,1,0,1,2.0,5.0,1006016P00014842
233580,233580,1006016,P00109542,M,46-50,1,B,1,0,8,14.0,17.0,1006016P00109542
233581,233581,1006018,P00071442,M,36-45,1,C,3,0,15,17.0,NaN,1006018P00071442
233582,233582,1006021,P00112542,M,26-35,12,B,2,0,1,11.0,15.0,1006021P00112542
233583,233583,1006021,P00003442,M,26-35,12,B,2,0,4,5.0,8.0,1006021P00003442
233584,233584,1006023,P00262242,M,26-35,0,C,2,0,1,11.0,16.0,1006023P00262242
233585,233585,1006025,P00161142,F,26-35,1,B,1,0,11,NaN,NaN,1006025P00161142
233586,233586,1006026,P00110742,M,36-45,6,C,1,0,1,2.0,8.0,1006026P00110742
233587,233587,1006028,P00162442,M,18-25,4,A,4+,0,1,16.0,NaN,1006028P00162442
233588,233588,1006030,P00129842,M,26-35,17,C,1,0,6,8.0,15.0,1006030P00129842
233589,233589,1006030,P00241442,M,26-35,17,C,1,0,2,15.0,NaN,1006030P00241442
233590,233590,1006032,P00252442,M,46-50,7,A,3,0,8,NaN,NaN,1006032P00252442
233591,233591,1006033,P00127642,M,51-55,13,B,1,0,1,2.0,15.0,1006033P00127642
233592,233592,1006035,P00135742,F,26-35,1,C,3,0,6,8.0,NaN,1006035P00135742
233593,233593,1006036,P00255442,F,26-35,15,B,4+,0,8,NaN,NaN,1006036P00255442
233594,233594,1006036,P00118942,F,26-35,15,B,4+,0,8,NaN,NaN,1006036P00118942
233595,233595,1006036,P00254642,F,26-35,15,B,4+,0,5,8.0,NaN,1006036P00254642
233596,233596,1006036,P00031842,F,26-35,15,B,4+,0,1,5.0,12.0,1006036P00031842
233597,233597,1006037,P00124742,F,46-50,1,C,4+,0,10,16.0,NaN,1006037P00124742
233598,233598,1006039,P00316642,F,46-50,0,B,4+,0,4,5.0,NaN,1006039P00316642

In [6]:
frames = [train, test]
df = pd.concat(frames)

print(df.shape)
df

(783667, 14)

,Age,City_Category,Comb,Gender,Marital_Status,Occupation,Product_Category_1,Product_Category_2,Product_Category_3,Product_ID,Purchase,Stay_In_Current_City_Years,Unnamed: 0,User_ID
0,0-17,A,NaN,F,0,10,3,NaN,NaN,P00069042,8370.0,2,NaN,1000001
1,0-17,A,NaN,F,0,10,1,6.0,14.0,P00248942,15200.0,2,NaN,1000001
2,0-17,A,NaN,F,0,10,12,NaN,NaN,P00087842,1422.0,2,NaN,1000001
3,0-17,A,NaN,F,0,10,12,14.0,NaN,P00085442,1057.0,2,NaN,1000001
4,55+,C,NaN,M,0,16,8,NaN,NaN,P00285442,7969.0,4+,NaN,1000002
5,26-35,A,NaN,M,0,15,1,2.0,NaN,P00193542,15227.0,3,NaN,1000003
6,46-50,B,NaN,M,1,7,1,8.0,17.0,P00184942,19215.0,2,NaN,1000004
7,46-50,B,NaN,M,1,7,1,15.0,NaN,P00346142,15854.0,2,NaN,1000004
8,46-50,B,NaN,M,1,7,1,16.0,NaN,P0097242,15686.0,2,NaN,1000004
9,26-35,A,NaN,M,1,20,8,NaN,NaN,P00274942,7871.0,1,NaN,1000005
10,26-35,A,NaN,M,1,20,5,11.0,NaN,P00251242,5254.0,1,NaN,1000005
11,26-35,A,NaN,M,1,20,8,NaN,NaN,P00014542,3957.0,1,NaN,1000005
12,26-35,A,NaN,M,1,20,8,NaN,NaN,P00031342,6073.0,1,NaN,1000005
13,26-35,A,NaN,M,1,20,1,2.0,5.0,P00145042,15665.0,1,NaN,1000005
14,51-55,A,NaN,F,0,9,5,8.0,14.0,P00231342,5378.0,1,NaN,1000006
15,51-55,A,NaN,F,0,9,4,5.0,NaN,P00190242,2079.0,1,NaN,1000006
16,51-55,A,NaN,F,0,9,2,3.0,4.0,P0096642,13055.0,1,NaN,1000006
17,51-55,A,NaN,F,0,9,5,14.0,NaN,P00058442,8851.0,1,NaN,1000006
18,36-45,B,NaN,M,1,1,1,14.0,16.0,P00036842,11788.0,1,NaN,1000007
19,26-35,C,NaN,M,1,12,1,5.0,15.0,P00249542,19614.0,4+,NaN,1000008
20,26-35,C,NaN,M,1,12,5,14.0,NaN,P00220442,8584.0,4+,NaN,1000008
21,26-35,C,NaN,M,1,12,8,NaN,NaN,P00156442,9872.0,4+,NaN,1000008
22,26-35,C,NaN,M,1,12,8,NaN,NaN,P00213742,9743.0,4+,NaN,1000008
23,26-35,C,NaN,M,1,12,8,NaN,NaN,P00214442,5982.0,4+,NaN,1000008
24,26-35,C,NaN,M,1,12,1,8.0,14.0,P00303442,11927.0,4+,NaN,1000008
25,26-35,C,NaN,M,0,17,6,8.0,NaN,P00135742,16662.0,0,NaN,1000009
26,26-35,C,NaN,M,0,17,8,NaN,NaN,P00039942,5887.0,0,NaN,1000009
27,26-35,C,NaN,M,0,17,5,14.0,NaN,P00161442,6973.0,0,NaN,1000009
28,26-35,C,NaN,M,0,17,5,8.0,14.0,P00078742,5391.0,0,NaN,1000009
29,36-45,B,NaN,F,1,1,2,4.0,8.0,P00085942,16352.0,4+,NaN,1000010
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
233569,26-35,B,1005996P00184242,F,0,0,9,15.0,NaN,P00184242,NaN,1,233569.0,1005996
233570,26-35,B,1005996P00045342,F,0,0,1,5.0,17.0,P00045342,NaN,1,233570.0,1005996
233571,26-35,A,1006001P00124642,F,0,7,16,NaN,NaN,P00124642,NaN,0,233571.0,1006001
233572,51-55,C,1006002P00121142,M,0,0,8,NaN,NaN,P00121142,NaN,1,233572.0,1006002
233573,51-55,C,1006002P00233542,M,0,0,1,15.0,NaN,P00233542,NaN,1,233573.0,1006002
233574,51-55,C,1006002P00226342,M,0,0,11,15.0,NaN,P00226342,NaN,1,233574.0,1006002
233575,51-55,C,1006002P00284842,M,0,0,1,8.0,17.0,P00284842,NaN,1,233575.0,1006002
233576,46-50,C,1006003P00313342,F,0,17,5,NaN,NaN,P00313342,NaN,1,233576.0,1006003
233577,36-45,C,1006010P00223542,M,0,0,1,8.0,17.0,P00223542,NaN,1,233577.0,1006010
233578,26-35,C,1006013P00020342,F,0,20,1,2.0,NaN,P00020342,NaN,3,233578.0,1006013
233579,46-50,B,1006016P00014842,M,0,1,1,2.0,5.0,P00014842,NaN,1,233579.0,1006016
233580,46-50,B,1006016P00109542,M,0,1,8,14.0,17.0,P00109542,NaN,1,233580.0,1006016
233581,36-45,C,1006018P00071442,M,0,1,15,17.0,NaN,P00071442,NaN,3,233581.0,1006018
233582,26-35,B,1006021P00112542,M,0,12,1,11.0,15.0,P00112542,NaN,2,233582.0,1006021
233583,26-35,B,1006021P00003442,M,0,12,4,5.0,8.0,P00003442,NaN,2,233583.0,1006021
233584,26-35,C,1006023P00262242,M,0,0,1,11.0,16.0,P00262242,NaN,2,233584.0,1006023
233585,26-35,B,1006025P00161142,F,0,1,11,NaN,NaN,P00161142,NaN,1,233585.0,1006025
233586,36-45,C,1006026P00110742,M,0,6,1,2.0,8.0,P00110742,NaN,1,233586.0,1006026
233587,18-25,A,1006028P00162442,M,0,4,1,16.0,NaN,P00162442,NaN,4+,233587.0,1006028
233588,26-35,C,1006030P00129842,M,0,17,6,8.0,15.0,P00129842,NaN,1,233588.0,1006030
233589,26-35,C,1006030P00241442,M,0,17,2,15.0,NaN,P00241442,NaN,1,233589.0,1006030
233590,46-50,A,1006032P00252442,M,0,7,8,NaN,NaN,P00252442,NaN,3,233590.0,1006032
233591,51-55,B,1006033P00127642,M,0,13,1,2.0,15.0,P00127642,NaN,1,233591.0,1006033
233592,26-35,C,1006035P00135742,F,0,1,6,8.0,NaN,P00135742,NaN,3,233592.0,1006035
233593,26-35,B,1006036P00255442,F,0,15,8,NaN,NaN,P00255442,NaN,4+,233593.0,1006036
233594,26-35,B,1006036P00118942,F,0,15,8,NaN,NaN,P00118942,NaN,4+,233594.0,1006036
233595,26-35,B,1006036P00254642,F,0,15,5,8.0,NaN,P00254642,NaN,4+,233595.0,1006036
233596,26-35,B,1006036P00031842,F,0,15,1,5.0,12.0,P00031842,NaN,4+,233596.0,1006036
233597,46-50,C,1006037P00124742,F,0,1,10,16.0,NaN,P00124742,NaN,4+,233597.0,1006037
233598,46-50,B,1006039P00316642,F,0,0,4,5.0,NaN,P00316642,NaN,4+,233598.0,1006039

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 783667 entries, 0 to 233598
Data columns (total 14 columns):
Age                           783667 non-null object
City_Category                 783667 non-null object
Comb                          233599 non-null object
Gender                        783667 non-null object
Marital_Status                783667 non-null int64
Occupation                    783667 non-null int64
Product_Category_1            783667 non-null int64
Product_Category_2            537685 non-null float64
Product_Category_3            237858 non-null float64
Product_ID                    783667 non-null object
Purchase                      550068 non-null float64
Stay_In_Current_City_Years    783667 non-null object
Unnamed: 0                    233599 non-null float64
User_ID                       783667 non-null int64
dtypes: float64(4), int64(4), object(6)
memory usage: 89.7+ MB

Let's find out how much missing values does each column have as a percentile representation.

In [8]:
df_nan = (df.isnull().sum() / df.shape[0]) * 100
df_nan[df_nan > 0]

Comb                  70.191548
Product_Category_2    31.388587
Product_Category_3    69.648078
Purchase              29.808452
Unnamed: 0            70.191548
dtype: float64

Let's handle the missing values by one by one columns and features.

Since,Comb is nothing but the combination of Product and User ID,let's drop it from the original dataframe for the sake of making a simpler dataframe.

In [9]:
df.drop('Comb',axis=1,inplace=True)
df.head(5)

,Age,City_Category,Gender,Marital_Status,Occupation,Product_Category_1,Product_Category_2,Product_Category_3,Product_ID,Purchase,Stay_In_Current_City_Years,Unnamed: 0,User_ID
0,0-17,A,F,0,10,3,NaN,NaN,P00069042,8370.0,2,NaN,1000001
1,0-17,A,F,0,10,1,6.0,14.0,P00248942,15200.0,2,NaN,1000001
2,0-17,A,F,0,10,12,NaN,NaN,P00087842,1422.0,2,NaN,1000001
3,0-17,A,F,0,10,12,14.0,NaN,P00085442,1057.0,2,NaN,1000001
4,55+,C,M,0,16,8,NaN,NaN,P00285442,7969.0,4+,NaN,1000002

Since,not sure about the Unnamed:0 what it does,therefore decided to drop this column as well.

In [10]:
df.drop('Unnamed: 0',axis=1,inplace=True)
df.head(5)

,Age,City_Category,Gender,Marital_Status,Occupation,Product_Category_1,Product_Category_2,Product_Category_3,Product_ID,Purchase,Stay_In_Current_City_Years,User_ID
0,0-17,A,F,0,10,3,NaN,NaN,P00069042,8370.0,2,1000001
1,0-17,A,F,0,10,1,6.0,14.0,P00248942,15200.0,2,1000001
2,0-17,A,F,0,10,12,NaN,NaN,P00087842,1422.0,2,1000001
3,0-17,A,F,0,10,12,14.0,NaN,P00085442,1057.0,2,1000001
4,55+,C,M,0,16,8,NaN,NaN,P00285442,7969.0,4+,1000002

# Now,let's do some feature engineering.

In [11]:
y=df['Purchase']
X=df['Occupation']

In [12]:
# Print the dimensions of X and y before reshaping
print("Dimensions of y before reshaping: {}".format(y.shape))
print("Dimensions of X before reshaping: {}".format(X.shape))

Dimensions of y before reshaping: (783667,)
Dimensions of X before reshaping: (783667,)

In [13]:
# Reshape X and y
y = y.reshape(-1,1)
X = X.reshape(-1,1)

# Print the dimensions of X and y after reshaping
#print(X)
print("Dimensions of y after reshaping: {}".format(y.shape))
print("Dimensions of X after reshaping: {}".format(X.shape))

Dimensions of y after reshaping: (783667, 1)
Dimensions of X after reshaping: (783667, 1)

C:\Users\owner\Anaconda3\lib\site-packages\ipykernel\__main__.py:2: FutureWarning: reshape is deprecated and will raise in a subsequent release. Please use .values.reshape(...) instead
  from ipykernel import kernelapp as app
C:\Users\owner\Anaconda3\lib\site-packages\ipykernel\__main__.py:3: FutureWarning: reshape is deprecated and will raise in a subsequent release. Please use .values.reshape(...) instead
  app.launch_new_instance()

In [14]:
np.isnan(X)

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]], dtype=bool)

In [15]:
np.where(np.isnan(X))

(array([], dtype=int64), array([], dtype=int64))

In [16]:
np.nan_to_num(X)

array([[10],
       [10],
       [10],
       ...,
       [15],
       [ 1],
       [ 0]], dtype=int64)

In [17]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)
reg_all=linear_model.LinearRegression()
reg_all.fit(X_train,y_train)
y_pred=reg_all.predict(X_train)

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

In [ ]:
# Import LinearRegression
from sklearn.linear_model import LinearRegression

# Create the regressor: reg
reg = LinearRegression()

# Create the prediction space
prediction_space = np.linspace(min(X), max(X)).reshape(-1,1)

# Fit the model to the data
reg.fit(X,y)

# Compute predictions over the prediction space: y_pred
y_pred = reg.predict(prediction_space)

# Print R^2 
print(reg.score(X,y))

# Plot regression line
plt.plot(prediction_space, y_pred, color='black', linewidth=3)
plt.show()

In [ ]:
df.info()

Replacing missing values with 999

In [ ]:
df.fillna(999,inplace=True)

In [ ]:
df.head()

In [ ]:
sns.heatmap(df.corr(), square=True, cmap='RdYlGn')
sns.despine()

Creating the target column

In [ ]:
target=df.Purchase

In [ ]:
target=np.array(target)
df.drop(['Purchase'],axis=1,inplace=True)

In [ ]:
df.head(2)

In [ ]:
target

In [ ]:
#Creating input variables for the model
input=df.applymap(str)
input

In [ ]:
input.info()

In [ ]:
input = np.array(input)

for i in range(input.shape[1]):
    lbl = preprocessing.LabelEncoder()
    lbl.fit(list(input[:,i]))
    input[:, i] = lbl.transform(input[:, i])

In [ ]:
input

In [ ]:
params = {}
params["min_child_weight"] = 10
params["subsample"] = 0.7
params["colsample_bytree"] = 0.7
params["scale_pos_weight"] = 0.8
params["silent"] = 0
params["max_depth"] = 6
params["nthread"] = 6
params["objective"] = "reg:linear"
params["eta"] = 0.1
params["base_score"] = 1800
params["eval_metric"] = "rmse"
params["seed"] = 0

plst = list(params.items())
num_rounds = 3000

In [ ]:
xgtrain = xgb.DMatrix(input[:train.shape[0],:], label=target[:train.shape[0]])
watchlist = [(xgtrain, 'train')]
model_1_xgboost = xgb.train(plst, xgtrain, num_rounds)

In [ ]:
model_1_predict = model_1_xgboost.predict(xgb.DMatrix(input[train.shape[0]:,:]))
model_1_predict[model_1_predict<0] = 25
submission.Purchase = model_1_predict
submission.to_csv("C:\\Users\\owner\\Documents\\Capstone Project-2\\SS.csv", index=False)